# Generated by Django 3.0.5 on 2020-05-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200520_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticolimodels',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='news.newsGiornalistiModels'),
        ),
    ]
